version: '3.8'

services:
  booking:
    build:
      context: ./booking
    ports:
      - "3003:3003"
    env_file:
      - ./booking/.env
    volumes:
      - ./booking:/app
    command: npm start
   

  otp:
    build:
      context: ./otp
    ports:
      - "3005:3005"
    env_file:
      - ./otp/.env
    volumes:
      - ./otp:/app
    command: npm start
    

  payment:
    build:
      context: ./payment
    ports:
      - "3004:3004"
    env_file:
      - ./payment/.env
    volumes:
      - ./payment:/app
    command: npm start
   
  seatselection:
    build:
      context: ./seatselection
    ports:
      - "3002:3002"
    env_file:
      - ./seatselection/.env
    volumes:
      - ./seatselection:/app
    command: npm start
    

  trainschedule:
    build:
      context: ./trainschedule
    ports:
      - "3001:3001"
    env_file:
      - ./trainschedule/.env
    volumes:
      - ./trainschedule:/app
    command: npm start
   

  user:
    build:
      context: ./user
    ports:
      - "3000:3000"
    env_file:
      - ./user/.env
    volumes:
      - ./user:/app
    command: npm start

